name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift build
        run: swift build

      - name: Build app bundle
        run: bash scripts/build-app.sh release
